version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
    target-branch: "develop"