version: "3.8"

services:
  nlp-tool:
    image: nlpsandbox/physical-address-annotator-example:0.3.2
    build:
      context: server
      dockerfile: Dockerfile
    container_name: physical-address-annotator
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/healthCheck
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nlp-sandbox-internal

  nginx:
    image: nginx:1.19.6-alpine
    container_name: physical-address-annotator-nginx
    restart: always
    environment:
      - TOOL_HOST=physical-address-annotator
      - TOOL_PORT=8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
    networks:
      - nlp-sandbox
      - nlp-sandbox-internal
    ports:
      - "80:80"
    depends_on:
      - physical-address-annotator

networks:
  nlp-sandbox:
  nlp-sandbox-internal:
    internal: true